// Code generated by hertz generator.

package main

import (
	"essay-platform/biz/infra/util/log"
	"essay-platform/provider"
	"net/http"

	"github.com/cloudwego/hertz/pkg/app/middlewares/server/recovery"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/obs-opentelemetry/tracing"
	"github.com/zeromicro/go-zero/core/logx"
	"go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
	"go.opentelemetry.io/contrib/propagators/b3"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/propagation"
)

func main() {
	provider.Init()
	logx.DisableStat()
	c := provider.Get().Config

	http.DefaultTransport = otelhttp.NewTransport(http.DefaultTransport)
	otel.SetTextMapPropagator(propagation.NewCompositeTextMapPropagator(b3.New(), propagation.Baggage{}, propagation.TraceContext{}))
	tracer, cfg := tracing.NewServerTracer()

	h := server.New(
		server.WithHostPorts(c.ListenOn),
		tracer,
	)
	h.Use(
		tracing.ServerMiddleware(cfg),
		recovery.Recovery(),
	)
	register(h)
	log.Info("server start")
	h.Spin()
}
