// Code generated by hertz generator. DO NOT EDIT.

package main

import (
	"essay-platform/biz/adaptor/controller"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", controller.Ping)

	// your code ...
}
