// Code generated by hertz generator.

package controller

import (
	"context"
	"essay-platform/biz/infra/util/log"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Ping .
func Ping(ctx context.Context, c *app.RequestContext) {
	log.Info("ping")
	c.JSON(consts.StatusOK, utils.H{
		"message": "pong",
	})
}
