// Code generated by hertz generator.

package sts

import (
	"context"
	"essay-platform/biz/adaptor"
	sts "essay-platform/biz/application/dto/sts"
	"essay-platform/provider"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// CreateOrder .
// @router /pay/create_order [POST]
func CreateOrder(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sts.CreateOrderReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.PayService.CreateOrder(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}
