// Code generated by hertz generator.

package sts

import (
	"context"
	"essay-platform/biz/adaptor"
	sts "essay-platform/biz/application/dto/sts"
	"essay-platform/provider"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GenCosSts .
// @router /sts/gen_cos_sts [POST]
func GenCosSts(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sts.GenCosStsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.CosService.GenCosSts(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// GenSignedUrl .
// @router /sts/gen_signed_url [POST]
func GenSignedUrl(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sts.GenSignedUrlReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.CosService.GenSignedUrl(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// SignIn .
// @router /sts/sign_in [POST]
func SignIn(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sts.SignInReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.AuthService.SignIn(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// SetPassword .
// @router /sts/set_password [POST]
func SetPassword(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sts.SetPasswordReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.AuthService.SetPassword(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// SendVerifyCode .
// @router /sts/send_verify_code [POST]
func SendVerifyCode(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sts.SendVerifyCodeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.AuthService.SendVerifyCode(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// AddAuth .
// @router /sts/add_auth [POST]
func AddAuth(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sts.AddAuthReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.AuthService.AddAuth(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// SendWechatMessage .
// @router /sts/send_wechat_message [POST]
func SendWechatMessage(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sts.SendWechatMessageReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.MessageService.SendWechatMessage(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// SignUp .
// @router /sts/sign_up [POST]
func SignUp(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sts.SignUpReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.AuthService.SignUp(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// GenerateUrlLink .
// @router /sts/generate_url_link [POST]
func GenerateUrlLink(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sts.GenerateUrlLinkReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.MessageService.GenerateUrlLink(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}
