// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"essay-platform/biz/application/service"
	"essay-platform/biz/infra/config"
	"essay-platform/biz/infra/mapper"
	"essay-platform/biz/infra/sdk/cos"
	"essay-platform/biz/infra/sdk/wechat"
	"essay-platform/biz/infra/stores/redis"
)

// Injectors from wire.go:

func NewProvider() (*Provider, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	cosSDK, err := cos.NewCosSDK(configConfig)
	if err != nil {
		return nil, err
	}
	userMapper := mapper.NewUserMapper(configConfig)
	miniProgramMap := wechat.NewWechatApplicationMap(configConfig)
	cosService := service.CosService{
		Config:         configConfig,
		CosSDK:         cosSDK,
		UserMapper:     userMapper,
		MiniProgramMap: miniProgramMap,
	}
	redisRedis := redis.NewRedis(configConfig)
	authenticationService := service.AuthenticationService{
		Config:         configConfig,
		UserMapper:     userMapper,
		MiniProgramMap: miniProgramMap,
		Redis:          redisRedis,
	}
	messageService := service.MessageService{
		Config:         configConfig,
		UserMapper:     userMapper,
		MiniProgramMap: miniProgramMap,
	}
	payMapper := mapper.NewPayMapper(configConfig)
	payService := service.PayService{
		Config:     configConfig,
		UserMapper: userMapper,
		PayMapper:  payMapper,
	}
	providerProvider := &Provider{
		Config:         configConfig,
		CosService:     cosService,
		AuthService:    authenticationService,
		MessageService: messageService,
		PayService:     payService,
	}
	return providerProvider, nil
}
