// Code generated by hertz generator.

package sts

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _stsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gencosstsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gensignedurlMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendverifycodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setpasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addauthMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendmessageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendwechatmessageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signupMw() []app.HandlerFunc {
	// your code...
	return nil
}
